name             'bb_jenkins'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures bb-jenkins'
long_description 'Installs/Configures bb-jenkins'
version          '0.1.0'

depends 'jenkins'
depends 'java'
